### PR TITLE
Handle unsafe host

### PR DESCRIPTION
**Pull request by sdsdkkk**
The vulnerability as descibed by @mikecmpbll 

```rb
# GET http://www.mywebsite.com/redirect?to[host]=http://dangerous.cn
# params[:to]
# => { host: "http://dangerous.cn" }
redirect_to params[:to]
```

### CODE REVIEW

**Comment by sdsdkkk** [comment]
@mikecmpbll what do you think if we handle it this way?

**Comment by mikecmpbll** [comment]
lgtm 👍🏼

thinking about this and the AR object issue, should we just consider anything passed to redirect_to that isn't a string or a hash as safe? realistically it's not come from params or anything like that unless it's a string or a hash. if we were to do that then redirect_to @post would work correctly.

part of me still thinks that checking the ultimate `location` header of the redirect would be the most complete solution, but this works for me too.

**Comment by sdsdkkk** [comment]
I also haven't thought of any possible problems with letting objects other than strings, symbols, and hashes pass the filter. I think we can just return the object as it is to support passing ActiveRecord object as the redirect target. I think I'll do that in another PR, and release the next build with the wildcard feature, this vulnerability fix, and support for ActiveRecord objects.

Looks like I really need to spare some time to look at Rails' code :sweat_smile:

**Comment by mikecmpbll** [comment]
thanks! these improvements have made it a viable gem for all my apps, i don't like the thought that i, or another dev, accidentally introduces vulns so i'd rather use this as an insurance policy 👍🏼. imo it should be built in to rails too, but i've not had any feedback from the rails team yet on this proposal.

**Comment by sdsdkkk** [comment]
Glad that there are other people who found this useful. I used to monkey-patch the Rails `redirect_to` implementation at work to prevent this vulnerability and decided to make it available as a plugin for others in case they have similar problems (and also to get feedback, since I alone would miss so many ways to bypass the filter).

As it's important not to introduce vulnerabilities during the development process, I agree that Rails should have a built-in support for this. It already has built-in support for like XSS and SQL injection prevention, so it'd be nice to also have built-in open redirect prevention :grinning:

**Pull request merged**
